Repository FundingBoost/FundingBoost-Server, pull requests merged in 2024-05, with the labels that each got.

#64 🔨 Refactor: bookmark로 이름 통일
  src/main/java/kcs/funding/fundingboost/domain/controller/BookmarkController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/wishList/BookmarkItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/wishList/MyBookmarkListDto.java
  src/main/java/kcs/funding/fundingboost/domain/service/BookmarkService.java
Labels: :hammer: Refactor

#69 🔨 Refactor: fundingItem을 생성할 때 funding에 fundingItem을 추가
  src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
Labels: :hammer: Refactor

#70 ✅ GiftHubController Junit Test 구현
  src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubController.java
  src/test/java/kcs/funding/fundingboost/domain/controller/GiftHubControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/model/GiftHubItemFixture.java
Labels: :white_check_mark: test

#71 ✅ ItemController Junit Test 구현
  src/test/java/kcs/funding/fundingboost/domain/controller/ItemControllerTest.java
Labels: :white_check_mark: test

#76 ✅ FundingController Junit Test 구현
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/friendFundingDetail/FriendFundingDetailDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/MyPageMemberDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/friendFundingHistory/FriendFundingContributionDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/myFundingHistory/MyPageFundingDetailHistoryDto.java
  src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/test/java/kcs/funding/fundingboost/domain/controller/FundingControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/model/FundingFixture.java
  src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTest.java
Labels: :white_check_mark: test

#78 ✅ 🔨 Test/Refactor: 창희 DeliveryService 테스트 코드 통합
  src/test/java/kcs/funding/fundingboost/domain/model/DeliveryFixture.java
  src/test/java/kcs/funding/fundingboost/domain/service/DeliveryServiceTest.java
Labels: :white_check_mark: test, :hammer: Refactor

#79 ✅ 🔨 Test/Refactor: 창희 exchangePoint 테스트 데이터 및 검증 추가
  src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
  src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/MemberService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/FriendPayService.java
  src/test/java/kcs/funding/fundingboost/domain/model/FundingFixture.java
  src/test/java/kcs/funding/fundingboost/domain/model/FundingItemFixture.java
  src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTest.java
  src/test/java/kcs/funding/fundingboost/domain/service/ItemServiceTest.java
  src/test/java/kcs/funding/fundingboost/domain/service/MemberServiceTest.java
  src/test/java/kcs/funding/fundingboost/domain/service/pay/FriendPayServiceTest.java
Labels: :white_check_mark: test, :hammer: Refactor

#80 ✅ 🔨 Test/Refactor: 창희 OrderController 테스트 코드 추가 및 Order/OrderItem totalPrice 추가 로직 refactor
  src/main/java/kcs/funding/fundingboost/domain/entity/Order.java
  src/main/java/kcs/funding/fundingboost/domain/entity/OrderItem.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
  src/test/java/kcs/funding/fundingboost/domain/controller/OrderControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/model/OrderFixture.java
Labels: :white_check_mark: test, :hammer: Refactor

#81 ✅ 🔨 Test/Refactor: 창희 MemberController 테스트 코드 통합
  src/main/java/kcs/funding/fundingboost/domain/controller/MemberController.java
  src/test/java/kcs/funding/fundingboost/domain/controller/MemberControllerTest.java
Labels: :white_check_mark: test, :hammer: Refactor

#77 ✅ 🔨 Test/Refactor: 재현이 GifthubItemService Test 코드 통합
  src/main/java/kcs/funding/fundingboost/domain/entity/GiftHubItem.java
  src/test/java/kcs/funding/fundingboost/domain/service/GiftHubItemServiceTest.java
Labels: :white_check_mark: test, :hammer: Refactor

#84 🔨 refactor: 마이페이지 내 펀딩 현황 funding message, tag 추가
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/myFundingStatus/MyFundingStatusDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
Labels: :hammer: Refactor

#85 🚑 HotFix: 충돌 에러 수정
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/home/HomeMyFundingStatusDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/home/HomeViewDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Contributor.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
  src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
  src/main/java/kcs/funding/fundingboost/domain/repository/giftHubItem/GiftHubItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/MemberService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/FriendPayService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
  src/main/java/kcs/funding/fundingboost/domain/service/utils/DateUtils.java
  src/main/java/kcs/funding/fundingboost/domain/service/utils/FundingConst.java
  src/main/java/kcs/funding/fundingboost/domain/service/utils/FundingUtils.java
  src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
  src/test/java/kcs/funding/fundingboost/domain/controller/DeliveryControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/FundingControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/GiftHubControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/OrderControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/model/FundingFixture.java
  src/test/java/kcs/funding/fundingboost/domain/model/FundingItemFixture.java
  src/test/java/kcs/funding/fundingboost/domain/model/GiftHubItemFixture.java
  src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTest.java
  src/test/java/kcs/funding/fundingboost/domain/service/MemberServiceTest.java
  src/test/java/kcs/funding/fundingboost/domain/service/pay/FriendPayServiceTest.java
Labels: :lady_beetle: bug, :white_check_mark: test, :hammer: Refactor

#86 🔨 refactor: initDB 리팩토링
  src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
Labels: :white_check_mark: test

#66 ✅ MyPayService Junit Test 구현
  src/test/java/kcs/funding/fundingboost/domain/model/DeliveryFixture.java
  src/test/java/kcs/funding/fundingboost/domain/model/FundingItemFixture.java
  src/test/java/kcs/funding/fundingboost/domain/service/pay/MyPayServiceTest.java
Labels: :white_check_mark: test

#63 ✅ 🔨 Test/Refactor :bookmark 페이지 조회 테스트 코드/ wish list 를 bookmark로 이름 통일
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/wishList/BookmarkItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/test/java/kcs/funding/fundingboost/domain/service/BookmarkServiceTest.java
Labels: :white_check_mark: test

#89 🔨 refactor: FundingService 메인 페이지 & 마이 펀딩 현황 조회에서 아이템 Percent 로직 오류 수정
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
Labels: :hammer: Refactor

#88 ✅ PayController(friendPayView, fundFriend) Test 코드 구현
  src/test/java/kcs/funding/fundingboost/domain/controller/MemberControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/OrderControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/PayControllerTest.java
Labels: :white_check_mark: test

#87 ✅ PayController Test 코드 구현
  src/main/java/kcs/funding/fundingboost/domain/controller/PayController.java
  src/test/java/kcs/funding/fundingboost/domain/controller/PayControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/model/DeliveryFixture.java
  src/test/java/kcs/funding/fundingboost/domain/service/DeliveryServiceTest.java
Labels: :white_check_mark: test

#90 ✅ 🔨 Test/Refactor: Utils 테스트 코드 작성 및 createDate, deadLine 관련 테스트 코드 수정
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/test/java/kcs/funding/fundingboost/domain/controller/FundingControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/service/utils/DateUtilsTest.java
  src/test/java/kcs/funding/fundingboost/domain/service/utils/FundingUtilsTest.java
  src/test/java/kcs/funding/fundingboost/domain/service/utils/PayUtilsTest.java
Labels: :white_check_mark: test, :hammer: Refactor

#95 ✨ 🔨 Feat/Refactor: 메인페이지 조회시 사용자 테그 출력/ 시간 차이를 이용하여 펀딩종료 표현을 하기 위해 시간차를 LocalDate -> LocalDateTime으로 변경 및 펀딩 종료명 수정
  src/main/java/kcs/funding/fundingboost/domain/dto/response/home/HomeMyFundingStatusDto.java
  src/main/java/kcs/funding/fundingboost/domain/service/utils/DateUtils.java
  src/main/java/kcs/funding/fundingboost/domain/service/utils/FundingConst.java
  src/test/java/kcs/funding/fundingboost/domain/service/utils/DateUtilsTest.java
Labels: :hammer: Refactor, :sparkles: Feature

#96 🔨 Refactor: 시간 차이를 이용하여 펀딩종료 상태요소 추가
  src/main/java/kcs/funding/fundingboost/domain/service/utils/DateUtils.java
Labels: :hammer: Refactor

#97 🔨 refactor: 친구 펀딩 상세 페이지 leftPrice, deadlineDate FriendFundingDetailDto…
  src/main/java/kcs/funding/fundingboost/domain/dto/response/friendFundingDetail/FriendFundingDetailDto.java
Labels: :hammer: Refactor

#91 ✅ 🔨 Test/Refactor: 창희 FundingService 테스트 코드 통합 및 리팩토링
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/friendFunding/FriendFundingDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
  src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/test/java/kcs/funding/fundingboost/domain/controller/FundingControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/PayControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/model/FundingFixture.java
  src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTestCH.java
Labels: :white_check_mark: test, :hammer: Refactor

#92 ✅ Test: 2차 main page 조회 test code 구현
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/test/java/kcs/funding/fundingboost/domain/model/RelationShipFixture.java
  src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTest_InHo_v2.java
Labels: :white_check_mark: test

#93 ✅ Test: Bookmark Controller test code 구현
  src/main/java/kcs/funding/fundingboost/domain/controller/BookmarkController.java
  src/test/java/kcs/funding/fundingboost/domain/controller/BookmarkControllerTest.java
Labels: :white_check_mark: test

#98 🔨 ✅ refactor: Delivery deliveryStatus 삭제 및 테스트 코드 오류 수정
  src/main/java/kcs/funding/fundingboost/domain/entity/Delivery.java
  src/test/java/kcs/funding/fundingboost/domain/model/FundingFixture.java
  src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTestCH.java
  src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTest_InHo_v2.java
Labels: :white_check_mark: test, :hammer: Refactor

#99 🔨 refactor: mypay fundingItem 배송지 입력하기에서 funding 진행중인 기준을 deadline으로 변경
  src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
Labels: :hammer: Refactor

#100 ✨ Feat/Setting: Refresh/Access Token 추가 및 redis 설정 추가
  build.gradle
  src/main/java/kcs/funding/fundingboost/domain/config/JwtSecurityConfig.java
  src/main/java/kcs/funding/fundingboost/domain/config/RedisConfig.java
  src/main/java/kcs/funding/fundingboost/domain/config/SecurityConfig.java
  src/main/java/kcs/funding/fundingboost/domain/controller/AuthController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/login/JwtAccessTokenDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/login/JwtRefreshTokenDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/login/TokenDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/login/UsernamePasswordJwtDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/member/Member.java
  src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
  src/main/java/kcs/funding/fundingboost/domain/security/controller/JwtAuthenticationController.java
  src/main/java/kcs/funding/fundingboost/domain/security/controller/SimpleAuthenticationController.java
  src/main/java/kcs/funding/fundingboost/domain/security/entity/BlackList.java
  src/main/java/kcs/funding/fundingboost/domain/security/entity/RefreshToken.java
  src/main/java/kcs/funding/fundingboost/domain/security/fliter/JwtFilter.java
  src/main/java/kcs/funding/fundingboost/domain/security/provider/JwtAuthenticationProvider.java
  src/main/java/kcs/funding/fundingboost/domain/security/provider/SimpleAuthenticationProvider.java
  src/main/java/kcs/funding/fundingboost/domain/security/repository/RefreshTokenRepository.java
  src/main/java/kcs/funding/fundingboost/domain/security/service/JwtAuthenticationService.java
  src/main/java/kcs/funding/fundingboost/domain/security/service/RedisTemplateService.java
  src/main/java/kcs/funding/fundingboost/domain/security/service/SimpleAuthenticationService.java
  src/main/java/kcs/funding/fundingboost/domain/security/utils/JwtUtils.java
  src/main/java/kcs/funding/fundingboost/domain/security/utils/SecurityConst.java
  src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
  src/main/resources/application.yml
  src/test/java/kcs/funding/fundingboost/domain/model/MemberFixture.java
Labels: :gear: Setting, :sparkles: Feature

#102 🔨 refactor: 쇼핑 페이지 : category 추가
  src/main/java/kcs/funding/fundingboost/domain/dto/response/shopping/ShopDto.java
  src/test/java/kcs/funding/fundingboost/domain/controller/BookmarkControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/FundingControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/model/RelationShipFixture.java
  src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTestCH.java
  src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTest_InHo_v2.java
Labels: :hammer: Refactor

#104 🔨 Refactor: GiftHub 페이지 조회할 때 GiftHubItemId 추가
  src/main/java/kcs/funding/fundingboost/domain/dto/response/giftHub/GiftHubDto.java
Labels: :hammer: Refactor

#105 🔨 refactor: home, 쇼핑, 쇼핑 디테일 페이지 로그인x 사용자 접근 허용
  src/main/java/kcs/funding/fundingboost/domain/config/SecurityConfig.java
  src/main/java/kcs/funding/fundingboost/domain/controller/ItemController.java
  src/main/java/kcs/funding/fundingboost/domain/security/resolver/JwtAuthorizationArgumentResolver.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/ItemService.java
Labels: :hammer: Refactor

#106 🔨 refactor: memberId @Login 어노테이션으로 수정 및 GiftHubCOntrollerTest 변경된 로직에 따른 parameter 값 수정
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/MemberController.java
  src/test/java/kcs/funding/fundingboost/domain/controller/GiftHubControllerTest.java
Labels: :hammer: Refactor

#107 ✅ 🔨 Test/Refactor : Jwt 적용에 따른 Controller 테스트 코드 수정
  src/main/java/kcs/funding/fundingboost/domain/config/SecurityConfig.java
  src/test/java/kcs/funding/fundingboost/domain/controller/BookmarkControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/DeliveryControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/FundingControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/GiftHubControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/ItemControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/MemberControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/OrderControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/PayControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/model/SecurityContextHolderFixture.java
Labels: :white_check_mark: test, :hammer: Refactor

#108 🔨 Feat/fb 109
  src/main/java/kcs/funding/fundingboost/domain/config/SecurityConfig.java
  src/main/java/kcs/funding/fundingboost/domain/security/resolver/JwtAuthorizationArgumentResolver.java
  src/main/java/kcs/funding/fundingboost/domain/security/utils/NoAuthPath.java
Labels: :hammer: Refactor

#109 ✨ Feat: oauth 2.0 로그인 추가
  .gitignore
  build.gradle
  src/main/java/kcs/funding/fundingboost/domain/config/AuthenticationConfig.java
  src/main/java/kcs/funding/fundingboost/domain/config/SecurityConfig.java
  src/main/java/kcs/funding/fundingboost/domain/config/WebMVCConfig.java
  src/main/java/kcs/funding/fundingboost/domain/dto/global/ResponseDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/login/LoginDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/login/JwtDto.java
  src/main/java/kcs/funding/fundingboost/domain/repository/MemberRepository.java
  src/main/java/kcs/funding/fundingboost/domain/security/CustomUserDetails.java
  src/main/java/kcs/funding/fundingboost/domain/security/CustomUserDetailsService.java
  src/main/java/kcs/funding/fundingboost/domain/security/KakaoOAuth2User.java
  src/main/java/kcs/funding/fundingboost/domain/security/controller/OAuth2AuthenticationController.java
  src/main/java/kcs/funding/fundingboost/domain/security/controller/SimpleAuthenticationController.java
  src/main/java/kcs/funding/fundingboost/domain/security/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/kcs/funding/fundingboost/domain/security/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kcs/funding/fundingboost/domain/security/provider/SimpleAuthenticationProvider.java
  src/main/java/kcs/funding/fundingboost/domain/security/service/SimpleAuthenticationService.java
  src/main/java/kcs/funding/fundingboost/domain/security/utils/NoAuthPath.java
  src/main/java/kcs/funding/fundingboost/domain/service/CustomOAuth2UserService.java
  src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
  src/main/resources/application.yml
  src/main/resources/templates/loginForm.html
Labels: :sparkles: Feature

#110 🔨 Refactor: git ignore 수정 및 swagger config Refresh Token 입력할 수 있도록 수정
  .gitignore
  build.gradle
  src/main/java/kcs/funding/fundingboost/domain/config/SwaggerConfig.java
  src/main/java/kcs/funding/fundingboost/domain/security/utils/NoAuthPath.java
  src/main/resources/application.yml
Labels: :hammer: Refactor

#111 🐞 fix : Redis AccessToken BlackList TTL 적용 안되는 버그 수정
  build.gradle
  src/main/java/kcs/funding/fundingboost/domain/security/entity/BlackList.java
  src/main/java/kcs/funding/fundingboost/domain/security/repository/BlackListRepository.java
  src/main/java/kcs/funding/fundingboost/domain/security/service/JwtAuthenticationService.java
  src/main/java/kcs/funding/fundingboost/domain/security/service/RedisTemplateService.java
  src/main/resources/application.yml
Labels: :lady_beetle: bug

#114 🔨 refactor: GiftHub 추가 로직 @Login memberId 수정
  src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/giftHub/AddGiftHubDto.java
  src/main/java/kcs/funding/fundingboost/domain/service/GiftHubItemService.java
  src/test/java/kcs/funding/fundingboost/domain/controller/GiftHubControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/service/GiftHubItemServiceTest.java
Labels: :white_check_mark: test, :hammer: Refactor

#112 ✨ Feat: GiftHubItem. Bookmark, Member Repository Test 구현
  src/main/java/kcs/funding/fundingboost/domain/repository/giftHubItem/GiftHubItemRepository.java
  src/test/java/kcs/funding/fundingboost/domain/model/BookmarkFixture.java
  src/test/java/kcs/funding/fundingboost/domain/repository/MemberRepositoryTest.java
  src/test/java/kcs/funding/fundingboost/domain/repository/bookmark/BookmarkRepositoryImplTest.java
  src/test/java/kcs/funding/fundingboost/domain/repository/bookmark/BookmarkRepositoryTest.java
  src/test/java/kcs/funding/fundingboost/domain/repository/giftHubItem/GiftHubItemRepositoryImplTest.java
  src/test/java/kcs/funding/fundingboost/domain/repository/giftHubItem/GiftHubItemRepositoryTest.java
  src/test/resources/application.yml
Labels: :white_check_mark: test

#118 ✨ Feat: Redis Lock Aop 추가
  build.gradle
  src/main/java/kcs/funding/fundingboost/domain/aop/lock/LockAspect.java
  src/main/java/kcs/funding/fundingboost/domain/aop/lock/RedisLock.java
  src/main/java/kcs/funding/fundingboost/domain/config/LockConfig.java
  src/main/java/kcs/funding/fundingboost/domain/config/RefreshTokenConfig.java
  src/main/java/kcs/funding/fundingboost/domain/entity/common/LockConst.java
  src/main/java/kcs/funding/fundingboost/domain/entity/lock/FundingLock.java
  src/main/java/kcs/funding/fundingboost/domain/repository/LockRepository.java
  src/main/java/kcs/funding/fundingboost/domain/security/provider/JwtAuthenticationProvider.java
  src/main/java/kcs/funding/fundingboost/domain/security/service/RedisTemplateService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/FriendPayService.java
  src/main/resources/application.yml
Labels: :sparkles: Feature

#116 ✅ Test: Delivery, Item, relationship, fundingItem repository 테스트 코드 작성
  src/main/java/kcs/funding/fundingboost/domain/repository/fundingItem/FundingItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/test/java/kcs/funding/fundingboost/domain/repository/DeliveryRepositoryTest.java
  src/test/java/kcs/funding/fundingboost/domain/repository/ItemRepositoryTest.java
  src/test/java/kcs/funding/fundingboost/domain/repository/fundingItem/FundingItemRepositoryTest.java
  src/test/java/kcs/funding/fundingboost/domain/repository/orderItem/OrderItemRepositoryImplTest.java
  src/test/java/kcs/funding/fundingboost/domain/repository/relationship/RelationshipRepositoryTest.java
  src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTestCH.java
  src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTest_InHo_v2.java
  src/test/resources/application.yml
Labels: :white_check_mark: test

#119 ✅ Test: FundingRepository Test Code 생성 및 중복된 기능의 QueryDsl 제거 및 기존 Jsql로 대체
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryCustom.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/service/MemberService.java
  src/test/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryTest.java
  src/test/java/kcs/funding/fundingboost/domain/service/MemberServiceTest.java
Labels: :white_check_mark: test

#121 :ambulance: [HotFix] dev 브랜치 에러 수정
  .gitignore
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/test/java/kcs/funding/fundingboost/domain/repository/bookmark/BookmarkRepositoryImplTest.java
  src/test/resources/application.yml
Labels: :lady_beetle: bug

#122 🔨 refactor: 마이페이지 조회 시 itemStatus 추가 및 deliveryListDto로 dto 이름 변경
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/myFundingStatus/MyPageFundingItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/pay/myPay/MyOrderPayViewDto.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/test/java/kcs/funding/fundingboost/domain/controller/FundingControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/controller/PayControllerTest.java
  src/test/java/kcs/funding/fundingboost/domain/service/pay/MyPayServiceTest.java
Labels: :lady_beetle: bug

#123 🔨 refactor: 마이페이지 My펀딩현황에서 FundingItemId 추가
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/myFundingStatus/MyPageFundingItemDto.java
Labels: :hammer: Refactor

#125 :rocket: [Depoly] 메트릭 수집을 위한 세팅 및 K8S 배포 환경을 위한 yml파일 리팩토링
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/kcs/funding/fundingboost/domain/config/GrafanaConfig.java
  src/main/java/kcs/funding/fundingboost/domain/security/utils/NoAuthPath.java
  src/main/java/kcs/funding/fundingboost/domain/service/BookmarkService.java
  src/main/java/kcs/funding/fundingboost/domain/service/DeliveryService.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/GiftHubItemService.java
  src/main/java/kcs/funding/fundingboost/domain/service/ItemService.java
  src/main/java/kcs/funding/fundingboost/domain/service/MemberService.java
  src/main/java/kcs/funding/fundingboost/domain/service/OrderService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/FriendPayService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
  src/main/resources/application-actuator.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-redis.yml
  src/main/resources/application-swagger.yml
  src/main/resources/application.yml
Labels: :earth_asia: Deploy

#127 :ambulance: [Conflict] conflict solved
  build.gradle
  src/main/java/kcs/funding/fundingboost/domain/config/CorsConfig.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Order.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryImpl.java
Labels: :hammer: Refactor

#124 ✨ Feat: 로그인시 친구목록 업데이트 및 신규 유저 친구목록 생성기능 추가
  build.gradle
  src/main/java/kcs/funding/fundingboost/domain/repository/MemberRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/CustomOAuth2UserService.java
  src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
Labels: :sparkles: Feature
