Repository FundingBoost/FundingBoost-Server, pull requests merged in 2024-04, with the labels that each got.

#8 ✨ Feat: 공통 Repository 생성 & Querydsl 설정 추가 & BaseTimeEntity 추가
  build.gradle
  src/main/java/kcs/funding/fundingboost/domain/config/AuditConfig.java
  src/main/java/kcs/funding/fundingboost/domain/config/QueryDslConfig.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Bookmark.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Contributor.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Delivery.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
  src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
  src/main/java/kcs/funding/fundingboost/domain/entity/GiftHubItem.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Order.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Relationship.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Review.java
  src/main/java/kcs/funding/fundingboost/domain/entity/common/BaseTimeEntity.java
  src/main/java/kcs/funding/fundingboost/domain/repository/BookmarkRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/ContributorRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/DeliveryRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/FundingItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/FundingRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/GiftHubItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/ItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/MemberRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/OrderRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/RelationshipRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/ReviewRepository.java
Labels: :gear: Setting

#9 ✨ Feat: GiftHub 페이지 조회 & dummy Data 추가
  src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
  src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubItemController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/GiftHubDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/GiftHubItem.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
  src/main/java/kcs/funding/fundingboost/domain/repository/GiftHubItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/GiftHubItemService.java
  src/main/resources/application.yml
Labels: :postbox: API, :sparkles: Feature

#10 ✨ Feat: 보일러 플레이팅 dto, exception 추가
  src/main/java/kcs/funding/fundingboost/domain/dto/global/ArgumentNotValidExceptionDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/global/ExceptionDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/global/ResponseDto.java
  src/main/java/kcs/funding/fundingboost/domain/exception/CommonException.java
  src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
  src/main/java/kcs/funding/fundingboost/domain/exception/GlobalExceptionHandler.java
Labels: :sparkles: Feature

#11 ✨ Feat: GiftHub 담기 기능 추가
  src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubItemController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/common/commonSuccessDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/AddGiftHubDto.java
  src/main/java/kcs/funding/fundingboost/domain/service/GiftHubItemService.java
Labels: :sparkles: Feature

#12 ✨ Feat: 쇼핑 페이지 조회
  src/main/java/kcs/funding/fundingboost/domain/controller/ItemController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/ShopDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/GiftHubItem.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
  src/main/java/kcs/funding/fundingboost/domain/service/ItemService.java
Labels: :sparkles: Feature

#16 ✨ Feat: 펀딩 종료하기 기능 추가
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
Labels: :sparkles: Feature

#14 ✨ Feat: Dummy Data 생성 및 MyPay 조회 페이지 생성
  src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/MyPayController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/DeliveryDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/FundingDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/HomeItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/HomeViewDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/ItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/MyPayViewDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Delivery.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Order.java
  src/main/java/kcs/funding/fundingboost/domain/repository/DeliveryRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/FundingItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/OrderRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/HomeService.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPayService.java
Labels: :sparkles: Feature

#19 🎨Refactor: ResponseDto로 return 수정
  src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
  src/main/java/kcs/funding/fundingboost/domain/controller/MyPayController.java
Labels: :hammer: Refactor

#18 ✨🎨 Feat/Refactor: 결제하기 구현 및 deliveryDto 수정
  src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
  src/main/java/kcs/funding/fundingboost/domain/controller/MyPayController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/PaymentDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/DeliveryDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Delivery.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
  src/main/java/kcs/funding/fundingboost/domain/service/PaymentService.java
Labels: :hammer: Refactor, :sparkles: Feature

#21 ✨ Feat: 친구 펀딩 결제 페이지 조회
  src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
  src/main/java/kcs/funding/fundingboost/domain/controller/FriendPayController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/DeliveryDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/FriendFundingPayingDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
  src/main/java/kcs/funding/fundingboost/domain/service/FriendPayService.java
Labels: :sparkles: Feature

#22 🔨Refactor: 더미 데이터 삽입
  src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
Labels: :hammer: Refactor

#24 ✨ Feat: 친구 펀딩 결제하기
  src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
  src/main/java/kcs/funding/fundingboost/domain/controller/FriendPayController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/FriendPayProcessDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
  src/main/java/kcs/funding/fundingboost/domain/service/FriendPayService.java
  src/main/java/kcs/funding/fundingboost/domain/service/ItemService.java
Labels: :sparkles: Feature

#25 🔨Refactor: Funding 객체로 찾는 걸 funding_id 키값을 이용하여 찾도록 수정
  src/main/java/kcs/funding/fundingboost/domain/repository/FundingItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPayService.java
Labels: :hammer: Refactor

#23 refactor: Funding 등록 페이지 조회 시 이미 Funding이 존재하면 Error코드 50002 분출 및 DTO…
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/RegisterFundingDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/RegisterFundingItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/ItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
Labels: :hammer: Refactor

#29 🔨Refactor: ERD 수정 반영하기 & 더미 데이터 배송지 추가
  src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Order.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPayService.java
Labels: :hammer: Refactor

#27 ✨🔨Feat/Refactor: 친구 펀딩 디테일 페이지 조회 구현/funding 객체가 아닌 fundingId를 이용하여 데이터를 가져오게끔 수정사항 반영
  src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/MyPayController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/ContributorDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/FriendFundingDetailDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/FriendFundingItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Contributor.java
  src/main/java/kcs/funding/fundingboost/domain/repository/ContributorRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/FundingItem/FundingItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/relationship/RelationshipRepositoryRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPayService.java
Labels: :hammer: Refactor, :sparkles: Feature

#32 🔨 Refactor: API 명세 수정에 따른 Contorller URL mapping 수정 및 주석 추가
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/HomeController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/ItemController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/MyPageController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/PayController.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
Labels: :hammer: Refactor

#34 🔨 refactor: 친구 목록 페이지 & 메인 페이지 조회 충돌 및 깃 dev 브랜치와 충돌 해결
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/RegisterFundingDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/RegisterFundingItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/CommonFriendFundingDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/FriendFundingDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/FriendFundingPageItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/HomeFriendFundingDto.java
  src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
  src/main/java/kcs/funding/fundingboost/domain/repository/FundingItem/FundingItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/repository/relationship/RelationshipRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/relationship/RelationshipRepositoryCustom.java
  src/main/java/kcs/funding/fundingboost/domain/repository/relationship/RelationshipRepositoryRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/HomeService.java
Labels: :hammer: Refactor

#33 ✨ feat: 마이페이지 조회 & FundingItem deliveryStatus 추가
  src/main/java/kcs/funding/fundingboost/domain/controller/MyPageController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/MyFundingStatusDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/MyPageFundingItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/MyPageMemberDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/ParticipateFriendDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
  src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
  src/main/java/kcs/funding/fundingboost/domain/repository/ContributorRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/FundingItem/FundingItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
Labels: :hammer: Refactor, :sparkles: Feature

#35 🔨 Refactor: 포인트 전환 & 펀딩 결제할 때 finished_status가 false가 되도록 리팩토링 & 펀딩 결제와 주문 결제 나누기
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/PayController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/FundingPaymentDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/MyPayDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/MyPageFundingItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
Labels: :hammer: Refactor

#38 ✨ Feat: 지난 펀딩 이력 조회
  src/main/java/kcs/funding/fundingboost/domain/controller/MyPageController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/CommonFriendFundingDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/FriendFundingDetailDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/MyFundingHistoryDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/MyFundingResponseDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Tag.java
  src/main/java/kcs/funding/fundingboost/domain/repository/Contributor/ContributorRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/Contributor/ContributorRepositoryCustom.java
  src/main/java/kcs/funding/fundingboost/domain/repository/Contributor/ContributorRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryCustom.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
Labels: :sparkles: Feature

#40 ✨ Feat: 지난 펀딩 이력 상세 조회 기능 개발
  src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
  src/main/java/kcs/funding/fundingboost/domain/controller/MyPageController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/MyFundingHistoryDetailDto.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
Labels: :sparkles: Feature

#39 ✨ Feat: 장바구니 아이템 수량 변경
  src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/ItemQuantityDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/GiftHubItem.java
  src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
  src/main/java/kcs/funding/fundingboost/domain/service/GiftHubItemService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
Labels: :sparkles: Feature

#41 ✨🔨Feat/Refactor: 상품 좋아요 / 에러 코드 추가 및 수정 / Optional 감싸서 반환하도록 변경
  src/main/java/kcs/funding/fundingboost/domain/controller/ItemController.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Bookmark.java
  src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
  src/main/java/kcs/funding/fundingboost/domain/repository/Bookmark/BookmarkRepositoryCustom.java
  src/main/java/kcs/funding/fundingboost/domain/repository/Bookmark/BookmarkRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryCustom.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/GiftHubItemService.java
  src/main/java/kcs/funding/fundingboost/domain/service/HomeService.java
  src/main/java/kcs/funding/fundingboost/domain/service/ItemService.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/FriendPayService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
Labels: :hammer: Refactor, :sparkles: Feature

#46 :ambulance: [HotFix] dev 에러 수정
  src/main/java/kcs/funding/fundingboost/domain/dto/response/MyPayViewDto.java
  src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
Labels: :lady_beetle: bug

#45 🔧 [Config] CORS 설정 추가
  src/main/java/kcs/funding/fundingboost/domain/config/CorsConfig.java
  src/main/java/kcs/funding/fundingboost/domain/config/WebMVCConfig.java
Labels: :gear: Setting

#42 ✨Feat: 잔여금액 결제 구현
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/PayController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/PayRemainDto.java
  src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
  src/main/java/kcs/funding/fundingboost/domain/repository/FundingItem/FundingItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/FriendPayService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
  src/main/java/kcs/funding/fundingboost/domain/service/utils/FundingConst.java
  src/main/java/kcs/funding/fundingboost/domain/service/utils/PayUtils.java
Labels: :sparkles: Feature

#44 📜 Docs: Repository package명 대문자에서 소문자로 변경
  src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubController.java
  src/main/java/kcs/funding/fundingboost/domain/repository/FundingItem/FundingItemRepositoryCustom.java
  src/main/java/kcs/funding/fundingboost/domain/repository/bookmark/BookmarkRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/bookmark/BookmarkRepositoryCustom.java
  src/main/java/kcs/funding/fundingboost/domain/repository/bookmark/BookmarkRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/repository/contributor/ContributorRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/contributor/ContributorRepositoryCustom.java
  src/main/java/kcs/funding/fundingboost/domain/repository/contributor/ContributorRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/repository/fundingItem/FundingItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/fundingItem/FundingItemRepositoryCustom.java
  src/main/java/kcs/funding/fundingboost/domain/repository/fundingItem/FundingItemRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/ItemService.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
Labels: :page_with_curl: Docs

#52 ✨ Feat: 마이페이지 배송지 관리 조회 기능 구현
  src/main/java/kcs/funding/fundingboost/domain/controller/MyPageController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/deliveryManage/MyPageDeliveryDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/deliveryManage/MyPageDeliveryManageDto.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
Labels: :sparkles: Feature

#53 ✨ feat: Gifthub 상품 삭제 기능 구현
  src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubController.java
  src/main/java/kcs/funding/fundingboost/domain/repository/GiftHubItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/GiftHubItemService.java
Labels: :sparkles: Feature

#47 🔨Refactor: 결제하기시 order, orderItem에 등록되도록 수정
  src/main/java/kcs/funding/fundingboost/domain/controller/PayController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/ItemPayDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/request/MyPayDto.java
  src/main/java/kcs/funding/fundingboost/domain/entity/Order.java
  src/main/java/kcs/funding/fundingboost/domain/repository/ItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/contributor/ContributorRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
Labels: :hammer: Refactor

#50 ✨Feat: 친구에게 펀딩한 목록 조회기능 구현
  src/main/java/kcs/funding/fundingboost/domain/controller/MyPageController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/friendFundingHistory/FriendFundingContributionDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/friendFundingHistory/FriendFundingHistoryDto.java
  src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
  src/main/java/kcs/funding/fundingboost/domain/repository/contributor/ContributorRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
Labels: :sparkles: Feature

#55 ✨Feat: feat: 위시리스트 조회 기능 구현
  src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/ItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/MyWishListDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/WishtListItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/repository/bookmark/BookmarkRepository.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
Labels: :sparkles: Feature

#56 🔨 Refactor : Funding deadline dto 수정
  src/main/java/kcs/funding/fundingboost/domain/dto/request/RegisterFundingDto.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
Labels: :hammer: Refactor

#57 :truck: [Move] service & controller 리팩토링 (HoneService, MyPageService 분리)
  src/main/java/kcs/funding/fundingboost/domain/controller/BookmarkController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/ContributorController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/DeliveryController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/HomeController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/MemberController.java
  src/main/java/kcs/funding/fundingboost/domain/controller/MyPageController.java
  src/main/java/kcs/funding/fundingboost/domain/service/ContributorService.java
  src/main/java/kcs/funding/fundingboost/domain/service/DeliveryService.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/main/java/kcs/funding/fundingboost/domain/service/HomeService.java
  src/main/java/kcs/funding/fundingboost/domain/service/MemberService.java
  src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
Labels: :hammer: Refactor

#60 🔨Refactor: merge 충돌 해결
  src/main/java/kcs/funding/fundingboost/domain/controller/BookmarkController.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/wishList/BookmarkListItemDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/wishList/MyBookmarkListDto.java
  src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/wishList/MyWishListDto.java
  src/main/java/kcs/funding/fundingboost/domain/service/BookmarkService.java
Labels: :hammer: Refactor

#48 :white_check_mark: Test: ItemService 테스트 코드 작성
  src/test/java/kcs/funding/fundingboost/domain/service/ItemServiceTest.java
Labels: :white_check_mark: test

#49 ✅ Test: OrderService 테스트 코드 작성
  src/test/java/kcs/funding/fundingboost/domain/service/OrderServiceTest.java
Labels: :white_check_mark: test

#51 ✅ Test: GiftHubItemService 테스트 코드 작성
  src/main/java/kcs/funding/fundingboost/domain/repository/giftHubItem/GiftHubItemRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/giftHubItem/GiftHubItemRepositoryCustom.java
  src/main/java/kcs/funding/fundingboost/domain/repository/giftHubItem/GiftHubItemRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
  src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
  src/test/java/kcs/funding/fundingboost/domain/service/GiftHubItemServiceTest.java
Labels: :white_check_mark: test

#54 ✅ Test: FriendPayService 테스트 코드 작성
  src/test/java/kcs/funding/fundingboost/domain/service/pay/FriendPayServiceTest.java
Labels: :white_check_mark: test
