Repository FundingBoost/FundingBoost-Server, pull requests merged in 2024-06, with the labels that each got.

#128 🔨 펀딩 종료했을 때 펀딩 아이템 finishStatus 변경 및 테스트 코드 변경 및 Oauth 코드 수정
  src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/domain/service/CustomOAuth2UserService.java
  src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
  src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTestCH.java
Labels: :white_check_mark: test, :hammer: Refactor

#132 🐞 Bug: kakao oauth 로그인시 마다 중복 생성되는 버그 수정
  src/main/java/kcs/funding/fundingboost/domain/repository/relationship/RelationshipRepository.java
  src/main/java/kcs/funding/fundingboost/domain/security/service/KaKaoLoginService.java
  src/main/java/kcs/funding/fundingboost/domain/security/utils/NoAuthPath.java
Labels: :lady_beetle: bug

#131 ✨ Feat: 전문 탐색 기능 추가
  build.gradle
  src/main/java/kcs/funding/fundingboost/domain/dto/response/shopping/ShopDto.java
  src/main/java/kcs/funding/fundingboost/domain/security/utils/NoAuthPath.java
  src/main/java/kcs/funding/fundingboost/domain/service/ItemService.java
  src/main/java/kcs/funding/fundingboost/elasticsearch/config/ElasticsearchConfig.java
  src/main/java/kcs/funding/fundingboost/elasticsearch/controller/SearchController.java
  src/main/java/kcs/funding/fundingboost/elasticsearch/index/ItemIndex.java
  src/main/java/kcs/funding/fundingboost/elasticsearch/repository/ItemIndexRepository.java
  src/main/java/kcs/funding/fundingboost/elasticsearch/repository/ItemIndexRepositoryCustom.java
  src/main/java/kcs/funding/fundingboost/elasticsearch/repository/ItemIndexRepositoryImpl.java
  src/main/java/kcs/funding/fundingboost/elasticsearch/service/ItemIndexService.java
  src/main/resources/application-elasticsearch.yml
  src/main/resources/application.yml
  src/test/java/kcs/funding/fundingboost/domain/controller/ItemControllerTest.java
Labels: :gear: Setting, :sparkles: Feature

#133 🔨 Refactor: CustomOAuth2UserService class 및 코드 제거, Member uuid -> kakaoId 변경, 친구목록 업데이트 리팩토링
  src/main/java/kcs/funding/fundingboost/domain/config/SecurityConfig.java
  src/main/java/kcs/funding/fundingboost/domain/entity/member/Member.java
  src/main/java/kcs/funding/fundingboost/domain/repository/MemberRepository.java
  src/main/java/kcs/funding/fundingboost/domain/repository/relationship/RelationshipRepository.java
  src/main/java/kcs/funding/fundingboost/domain/security/service/KaKaoLoginService.java
  src/main/java/kcs/funding/fundingboost/domain/service/CustomOAuth2UserService.java
  src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
Labels: :hammer: Refactor
